### ISSUE TITLE
Argument parsing

### ISSUE THREAD

**Issue by kzoltaan** [funbiscuit/embedded-cli#1]
Hi. 

Your library is very cool. I'm using it in my hobby project in ESP-IDF. Can you solve somehow the quoted arguments?

<pre>
mycmd "this is my arg" 123
//---
//command is mycmd, first arg is "this is my arg" and other is 123.
</pre>

This would be nice.

**Comment by funbiscuit** [comment]
Hi!

Thanks for your feedback. I'll think about it and will try to add this feature, it doesn't seem very hard to add.

**Comment by funbiscuit** [comment]
Quoted args now supported with latest commit. Checkout readme for examples on how they work.

**Comment by kzoltaan** [comment]
Looks GOOD!!!!!!  Thanks!
