### ISSUE TITLE
win32-example doesn't check for malloc failure

### ISSUE THREAD

**Issue by schaefer01** [funbiscuit/embedded-cli#12]
Since cli depends on malloc, calls to instantiate the cli should first check for malloc fail.

in main.cpp:

EmbeddedCli *cli = embeddedCliNewDefault();  

cli->onCommand = ...

**Comment by funbiscuit** [comment]
Hi! It's a good point, but I don't see this necessary here. I think that malloc failing to allocate ~200 bytes on windows is highly unlikely. And even if it fails, whole program will crash on the next line, I think it's a normal behavior. Since cli is the only reason to run this program
