### ISSUE TITLE
Length of buffer can cause overwritting config struct

### ISSUE THREAD

**Issue by PeterWaIIace** [funbiscuit/embedded-cli#13]
https://github.com/funbiscuit/embedded-cli/blob/4ba7596a518814179b698bd8c0c73fb400e3a74e/examples/arduino-cli/arduino-cli.ino#L32

I used sligthly edited code from example in nrf52840 build.  I think I was able to spot potential bug. 

Using: `BYTES_TO_CLI_UINTS(CLI_BUFFER_SIZE)` for static allocation of cliBuffer, and  `totalSize` in  `embeddedCliNew` for memset can cause  overwritting config struct with zeros. It doesn't cause problems as long as buffer is allocated in memory after struct. 

In case buffer is allocated before struct it can set zeros to entire config struct while calling `embeddedCliNew` due to starting address of `cliBuffer` being only `BYTES_TO_CLI_UINTS(CLI_BUFFER_SIZE)` bytes before config struct.

It happened on nrf52840. I could neither isolate any causing allocation issue compiler flags, nor replicate it in other systems.

**Comment by funbiscuit** [comment]
Can you print-debug actual values of:

```
sizeof(CLI_UINT)
BYTES_TO_CLI_UINTS(CLI_BUFFER_SIZE)
CLI_BUFFER_SIZE
embeddedCliRequiredSize(yourConfig)
```

when you see that config was overwritten. Also please specify which version (commit would be the best) of library do you use.

**Comment by PeterWaIIace** [comment]
Thanks for quick response. I have used the release version v0.1.1. I believe it is: https://github.com/funbiscuit/embedded-cli/commit/4ba7596a518814179b698bd8c0c73fb400e3a74e

here are the values: 

```
00> <debug> app: sizeof(CLI_UINT): 4
00> <debug> app: BYTES_TO_CLI_UINTS(CLI_BUFFER_SIZE): 41
00> <debug> app: CLI_BUFFER_SIZE: 164
00> <debug> app: embeddedCliRequiredSize(yourConfig): 340
```

The initialization is same as in the example.

**Comment by funbiscuit** [comment]
Are you checking if embeddedCliNew returned null? It should return null indicating it failed because size of your buffer is less than embeddedCliRequiredSize
Or in your case it is returning non null pointer?

**Comment by funbiscuit** [comment]
Oh, I think I found the problem. You are using this line, right?

config->cliBufferSize = CLI_BUFFER_SIZE * sizeof(CLI_UINT);
   

It's incorrect, it should be
config->cliBufferSize = CLI_BUFFER_SIZE;

**Comment by PeterWaIIace** [comment]
It didn't returned null. Entire initialization goes as intended except config is overwritten by zeros.

I used the code from Arduino example.

I will check your solution. Thanks!
