### ISSUE TITLE
Invalid CMake settings for compiling as a library and using C

### ISSUE THREAD

**Issue by SeanAlling-DojoFive** [funbiscuit/embedded-cli#31]
## Describe the bug

Using a CMake project configured for C source code only, `CMAKE_CXX_COMPILER_ID` is undefined resulting in 
a warning being printed to terminal, "Can't enable extra flags for compiler  ". 

Compiler used for project is `arm-none-eabi-gcc`

## To Reproduce

Assuming `embedded-cli` is a git submodule, from root CMakeLists.txt, include `add_subdirectory(embedded-cli)` line to build `embedded-cli` as a library. 

Generate CMake environment. During generation, CMake will print warning "Can't enable extra flags for compiler  ". 

## Expected behavior

No warning should be printed, and `embedded-cli` flags should be added to GNU compiler.

## Resolution
Embedded-cli is configured as a C project

```
project(embedded_cli C)
```

The above does not include `CXX`, as such, `CMAKE_CXX_COMPILER_ID` will never be populated. 

Two methods can be used to resolve bug:
1. Add `CXX` to project
    ```
    project(embedded_cli C CXX)
    ```
2. Change `CMAKE_CXX_COMPILER_ID` to `CMAKE_C_COMPILER_ID`

Option 2 should be preffered as embedded-cli uses C source files and not C++.

**Comment by funbiscuit** [comment]
Thanks for picking that up! In CI tests are always enabled so CXX compiler was always available. I've merged #32 that fixes this.
