### ISSUE TITLE
Compiler warning when compiled with -Wall

### ISSUE THREAD

**Issue by pfvogel** [funbiscuit/embedded-cli#4]
I pulled your code into a project I'm writing now and it works great, thanks for providing this, it was exactly what I was looking for.

Compiling the code with a old gcc 5.4.0 cross compiler with the -Wall flag gives one warning:

embedded-cli/lib/src/embedded_cli.c:7:20: warning: unused variable 'impl' [-Wunused-variable]
   EmbeddedCliImpl* impl = (EmbeddedCliImpl*)t->_impl;
                    ^
embedded-cli/lib/src/embedded_cli.c:803:5: note: in expansion of macro 'PREPARE_IMPL'
     PREPARE_IMPL(cli)
     ^

It looks like the PREPARE_IMPL macro does not need to be called in the initInternalBindings() routine.

Thanks!

**Comment by funbiscuit** [comment]
It looks like you're not using the latest version. In master there is no PREPARE_IMPL on line 803:

```c
SET_FLAG(impl->flags, CLI_FLAG_DIRECT_PRINT);
```

Currently project already compiles with -Wall and -Werror (look in CMakeLists.txt for a full list of flags, there are plenty) so all issues should be fixed.

**Comment by pfvogel** [comment]
You're right, I had cloned the project right before this change was made and I hadn't checked the latest release.  Sorry for the bother and thanks again for providing this.
