### ISSUE TITLE
Make Auto Completion Optional

### ISSUE THREAD

**Issue by ASMPPM** [funbiscuit/embedded-cli#8]
Hi,
could you please make auto completion optional by a flag e.g. in the NewEmbeddedCLI construction and/or an activation/deactivation function?
This would help to be able to use the interface for human operators at the start and switch to e.g. scripted commands from a computer alter.

Cheers
Philipp

**Comment by asuar078** [comment]
I had the same issue when I tried to use the cli from a python script. 
#9 started a pull request to try and add that option.

**Comment by funbiscuit** [comment]
Thanks for your feedback! Fixed in #10
